name: Update from Overpass API

on: 
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:

jobs:
  overpass-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: wget
      run: wget --post-file=query.xml -O data.json http://overpass-api.de/api/interpreter
    - name: commit
      run: |
          git config --global user.name 'Overpass Update (bot)'
          git config --global user.email 'ffaadd-dk@users.noreply.github.com'
          git commit -am "Update from Overpass API"
          git push
    
